[build]
  command = "npm install --no-save netlify-plugin-php@^1.0.4 && composer install --no-dev --optimize-autoloader"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-php"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
